-- Available extensions
SELECT * FROM PG_Available_Extensions ORDER BY name ASC;

-- Installed extensions
SELECT * FROM PG_Extension ORDER BY extname ASC;

-- Drop extensions
DROP EXTENSION IF EXISTS mtree1 CASCADE;
DROP EXTENSION IF EXISTS mtree2 CASCADE;
DROP EXTENSION IF EXISTS mtree3 CASCADE;
DROP EXTENSION IF EXISTS mtree4 CASCADE;
DROP EXTENSION IF EXISTS mtree5 CASCADE;
DROP EXTENSION IF EXISTS mtree6 CASCADE;
DROP EXTENSION IF EXISTS mtree7 CASCADE;
DROP EXTENSION IF EXISTS mtree8 CASCADE;

-- Create extensions
CREATE EXTENSION mtree1;
CREATE EXTENSION mtree2;
CREATE EXTENSION mtree3;
CREATE EXTENSION mtree4;
CREATE EXTENSION mtree5;
CREATE EXTENSION mtree6;
CREATE EXTENSION mtree7;
CREATE EXTENSION mtree8;
